//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_FAScheduleBill {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_FAScheduleBill() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_FAScheduleBill", typeof(VT_FAScheduleBill).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实际装配数 的本地化字符串。
        /// </summary>
        public static string ActualAssemblyNum {
            get {
                return ResourceManager.GetString("ActualAssemblyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装调度单 的本地化字符串。
        /// </summary>
        public static string AssembleDispatch {
            get {
                return ResourceManager.GetString("AssembleDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装中计划 的本地化字符串。
        /// </summary>
        public static string AssembleMiddlePlanTabTitle {
            get {
                return ResourceManager.GetString("AssembleMiddlePlanTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装排产（中计划） 的本地化字符串。
        /// </summary>
        public static string AssembleMiddlePlanTitle {
            get {
                return ResourceManager.GetString("AssembleMiddlePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装计划一览详细 的本地化字符串。
        /// </summary>
        public static string AssemblePlanDetail {
            get {
                return ResourceManager.GetString("AssemblePlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装计划一览 的本地化字符串。
        /// </summary>
        public static string AssemblePlanTitle {
            get {
                return ResourceManager.GetString("AssemblePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装数量 的本地化字符串。
        /// </summary>
        public static string AssembleQuanlity {
            get {
                return ResourceManager.GetString("AssembleQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单号 的本地化字符串。
        /// </summary>
        public static string AssemblyDispatchID {
            get {
                return ResourceManager.GetString("AssemblyDispatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划装配数 的本地化字符串。
        /// </summary>
        public static string AssemblyPlanNum {
            get {
                return ResourceManager.GetString("AssemblyPlanNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划装配数量 的本地化字符串。
        /// </summary>
        public static string AssemblyPlanNumD {
            get {
                return ResourceManager.GetString("AssemblyPlanNumD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装工票号码 的本地化字符串。
        /// </summary>
        public static string AssemblyTicketID {
            get {
                return ResourceManager.GetString("AssemblyTicketID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string BatchNumber {
            get {
                return ResourceManager.GetString("BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string ConstQty {
            get {
                return ResourceManager.GetString("ConstQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string CustomerOrderNum {
            get {
                return ResourceManager.GetString("CustomerOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度员 的本地化字符串。
        /// </summary>
        public static string Dispatcher {
            get {
                return ResourceManager.GetString("Dispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单号 的本地化字符串。
        /// </summary>
        public static string DispatchId {
            get {
                return ResourceManager.GetString("DispatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态 的本地化字符串。
        /// </summary>
        public static string DispatchStatus {
            get {
                return ResourceManager.GetString("DispatchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零件略称 的本地化字符串。
        /// </summary>
        public static string ExportAbbrev {
            get {
                return ResourceManager.GetString("ExportAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装调度单一览 的本地化字符串。
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质检员 的本地化字符串。
        /// </summary>
        public static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料数量 的本地化字符串。
        /// </summary>
        public static string MaterialQuanlity {
            get {
                return ResourceManager.GetString("MaterialQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成大工票 的本地化字符串。
        /// </summary>
        public static string NewFAWorkticket {
            get {
                return ResourceManager.GetString("NewFAWorkticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装 的本地化字符串。
        /// </summary>
        public static string PackingFirst {
            get {
                return ResourceManager.GetString("PackingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string PackingSecond {
            get {
                return ResourceManager.GetString("PackingSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品批次号 的本地化字符串。
        /// </summary>
        public static string PackingThird {
            get {
                return ResourceManager.GetString("PackingThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称型号 的本地化字符串。
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划交期 的本地化字符串。
        /// </summary>
        public static string PlanDeliveryDate {
            get {
                return ResourceManager.GetString("PlanDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装调度单打印预览 的本地化字符串。
        /// </summary>
        public static string PrintViewTitle {
            get {
                return ResourceManager.GetString("PrintViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string ProdAbbrev {
            get {
                return ResourceManager.GetString("ProdAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产单元 的本地化字符串。
        /// </summary>
        public static string ProductionUnits {
            get {
                return ResourceManager.GetString("ProductionUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际在库数量 的本地化字符串。
        /// </summary>
        public static string RealInQuanlity {
            get {
                return ResourceManager.GetString("RealInQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下单日期 的本地化字符串。
        /// </summary>
        public static string SchedulingOrderDate {
            get {
                return ResourceManager.GetString("SchedulingOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称代码 的本地化字符串。
        /// </summary>
        public static string SubItemID {
            get {
                return ResourceManager.GetString("SubItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班组 的本地化字符串。
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        public static string TotalNumberOfSets1 {
            get {
                return ResourceManager.GetString("TotalNumberOfSets1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套 的本地化字符串。
        /// </summary>
        public static string TotalNumberOfSets2 {
            get {
                return ResourceManager.GetString("TotalNumberOfSets2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打字 的本地化字符串。
        /// </summary>
        public static string TypingContent {
            get {
                return ResourceManager.GetString("TypingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装箱入库数量 的本地化字符串。
        /// </summary>
        public static string WareHouseBox {
            get {
                return ResourceManager.GetString("WareHouseBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱× 的本地化字符串。
        /// </summary>
        public static string WareHouseBoxCer1 {
            get {
                return ResourceManager.GetString("WareHouseBoxCer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套/箱 的本地化字符串。
        /// </summary>
        public static string WareHouseBoxCer2 {
            get {
                return ResourceManager.GetString("WareHouseBoxCer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库日期 的本地化字符串。
        /// </summary>
        public static string WareHouseDate {
            get {
                return ResourceManager.GetString("WareHouseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品管理员 的本地化字符串。
        /// </summary>
        public static string WareHouseKeeperID {
            get {
                return ResourceManager.GetString("WareHouseKeeperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套(零头) 的本地化字符串。
        /// </summary>
        public static string WareHouseOdd {
            get {
                return ResourceManager.GetString("WareHouseOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓人 的本地化字符串。
        /// </summary>
        public static string WareHousePerson {
            get {
                return ResourceManager.GetString("WareHousePerson", resourceCulture);
            }
        }
    }
}
