//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_InProcessing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_InProcessing() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_InProcessing", typeof(VT_InProcessing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据处理中...... 的本地化字符串。
        /// </summary>
        public static string DataProcessing {
            get {
                return ResourceManager.GetString("DataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟 的本地化字符串。
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延误 的本地化字符串。
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成日 的本地化字符串。
        /// </summary>
        public static string FinishDay {
            get {
                return ResourceManager.GetString("FinishDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工计划一览 的本地化字符串。
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成中 的本地化字符串。
        /// </summary>
        public static string Ing {
            get {
                return ResourceManager.GetString("Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工排产（小计划） 的本地化字符串。
        /// </summary>
        public static string LittlePlanTitle {
            get {
                return ResourceManager.GetString("LittlePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料数量 的本地化字符串。
        /// </summary>
        public static string MaterialQuanlity {
            get {
                return ResourceManager.GetString("MaterialQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工排产（中计划） 的本地化字符串。
        /// </summary>
        public static string MiddlePlanTitle {
            get {
                return ResourceManager.GetString("MiddlePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未生产 的本地化字符串。
        /// </summary>
        public static string NotProduce {
            get {
                return ResourceManager.GetString("NotProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零部件名称 的本地化字符串。
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排&amp;nbsp;产&amp;nbsp;状&amp;nbsp;态 的本地化字符串。
        /// </summary>
        public static string PlanState {
            get {
                return ResourceManager.GetString("PlanState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预排产计划 的本地化字符串。
        /// </summary>
        public static string PredictScheduPlan {
            get {
                return ResourceManager.GetString("PredictScheduPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工排产 的本地化字符串。
        /// </summary>
        public static string ProcessPlan {
            get {
                return ResourceManager.GetString("ProcessPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工中计划 的本地化字符串。
        /// </summary>
        public static string ProcessPlanTabTitle {
            get {
                return ResourceManager.GetString("ProcessPlanTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工排产（中计划） 的本地化字符串。
        /// </summary>
        public static string ProcessPlanTitle {
            get {
                return ResourceManager.GetString("ProcessPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产计划/实际 的本地化字符串。
        /// </summary>
        public static string ProducePlan_Real {
            get {
                return ResourceManager.GetString("ProducePlan_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工数量 的本地化字符串。
        /// </summary>
        public static string ProduceQuanlity {
            get {
                return ResourceManager.GetString("ProduceQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提&amp;nbsp;供&amp;nbsp;日&amp;nbsp;期 的本地化字符串。
        /// </summary>
        public static string ProvideDate {
            get {
                return ResourceManager.GetString("ProvideDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供日 的本地化字符串。
        /// </summary>
        public static string ProvideDay {
            get {
                return ResourceManager.GetString("ProvideDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Quanlity {
            get {
                return ResourceManager.GetString("Quanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划需求&lt;br/&gt;数量 的本地化字符串。
        /// </summary>
        public static string ScheduNeedQuanlity {
            get {
                return ResourceManager.GetString("ScheduNeedQuanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排产计划 的本地化字符串。
        /// </summary>
        public static string ScheduPlan {
            get {
                return ResourceManager.GetString("ScheduPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度状态 的本地化字符串。
        /// </summary>
        public static string ScheduState {
            get {
                return ResourceManager.GetString("ScheduState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的记录中含有多种\&quot;&lt;font style=&apos;color:red&apos;&gt;零件型号&lt;/font&gt;\&quot;，请重新选择 的本地化字符串。
        /// </summary>
        public static string SelectedMoreExportMessage {
            get {
                return ResourceManager.GetString("SelectedMoreExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料和规格要求 的本地化字符串。
        /// </summary>
        public static string Specifica {
            get {
                return ResourceManager.GetString("Specifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动日 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日 的本地化字符串。
        /// </summary>
        public static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工流转卡计划 的本地化字符串。
        /// </summary>
        public static string TranslationCardPlan {
            get {
                return ResourceManager.GetString("TranslationCardPlan", resourceCulture);
            }
        }
    }
}
