//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_InProcessingWarehouseList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_InProcessingWarehouseList() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_InProcessingWarehouseList", typeof(VT_InProcessingWarehouseList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开单日期 的本地化字符串。
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓日期 的本地化字符串。
        /// </summary>
        public static string BillDt {
            get {
                return ResourceManager.GetString("BillDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让步标志 的本地化字符串。
        /// </summary>
        public static string ConcessionPart {
            get {
                return ResourceManager.GetString("ConcessionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否让步接收 的本地化字符串。
        /// </summary>
        public static string ConcessionPartD {
            get {
                return ResourceManager.GetString("ConcessionPartD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工单位 的本地化字符串。
        /// </summary>
        public static string DepartName {
            get {
                return ResourceManager.GetString("DepartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        public static string DetailInformation {
            get {
                return ResourceManager.GetString("DetailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余料 的本地化字符串。
        /// </summary>
        public static string ExcessQuantity {
            get {
                return ResourceManager.GetString("ExcessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工交仓单一览 的本地化字符串。
        /// </summary>
        public static string IIndexTitle {
            get {
                return ResourceManager.GetString("IIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工产品交仓单 的本地化字符串。
        /// </summary>
        public static string IIndexTitleDetail {
            get {
                return ResourceManager.GetString("IIndexTitleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工产品交仓单一览详细 的本地化字符串。
        /// </summary>
        public static string InProWarListDet {
            get {
                return ResourceManager.GetString("InProWarListDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺料 的本地化字符串。
        /// </summary>
        public static string LackQuantity {
            get {
                return ResourceManager.GetString("LackQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人 的本地化字符串。
        /// </summary>
        public static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        public static string PlanTotal {
            get {
                return ResourceManager.GetString("PlanTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工产品交仓单打印一览 的本地化字符串。
        /// </summary>
        public static string PrintViewTitle {
            get {
                return ResourceManager.GetString("PrintViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓单号 的本地化字符串。
        /// </summary>
        public static string ProcDelivID {
            get {
                return ResourceManager.GetString("ProcDelivID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 的本地化字符串。
        /// </summary>
        public static string ProcDelivIDD {
            get {
                return ResourceManager.GetString("ProcDelivIDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工工艺 的本地化字符串。
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流转卡号 的本地化字符串。
        /// </summary>
        public static string ProcessTranID {
            get {
                return ResourceManager.GetString("ProcessTranID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格 的本地化字符串。
        /// </summary>
        public static string QualifiedQuantity {
            get {
                return ResourceManager.GetString("QualifiedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量验收员 的本地化字符串。
        /// </summary>
        public static string QualityInspector {
            get {
                return ResourceManager.GetString("QualityInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废 的本地化字符串。
        /// </summary>
        public static string ScrapQuantity {
            get {
                return ResourceManager.GetString("ScrapQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领产品型号 的本地化字符串。
        /// </summary>
        public static string SubItemName {
            get {
                return ResourceManager.GetString("SubItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓管员 的本地化字符串。
        /// </summary>
        public static string WarehKprName {
            get {
                return ResourceManager.GetString("WarehKprName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库状态 的本地化字符串。
        /// </summary>
        public static string WarehouseStatus {
            get {
                return ResourceManager.GetString("WarehouseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓数量 的本地化字符串。
        /// </summary>
        public static string WarehQtySubmitted {
            get {
                return ResourceManager.GetString("WarehQtySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料费 的本地化字符串。
        /// </summary>
        public static string WasteQuantity {
            get {
                return ResourceManager.GetString("WasteQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
