//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_IWaitingWarehouseList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_IWaitingWarehouseList() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_IWaitingWarehouseList", typeof(VT_IWaitingWarehouseList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 是否让步接受 的本地化字符串。
        /// </summary>
        public static string ConcessionPart {
            get {
                return ResourceManager.GetString("ConcessionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待交仓一览 的本地化字符串。
        /// </summary>
        public static string IIndexTitle {
            get {
                return ResourceManager.GetString("IIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料数量 的本地化字符串。
        /// </summary>
        public static string MaterReqQty {
            get {
                return ResourceManager.GetString("MaterReqQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓 的本地化字符串。
        /// </summary>
        public static string PostPositions {
            get {
                return ResourceManager.GetString("PostPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流转卡号 的本地化字符串。
        /// </summary>
        public static string ProcDelivID {
            get {
                return ResourceManager.GetString("ProcDelivID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string ProdAbbrev {
            get {
                return ResourceManager.GetString("ProdAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓单号 的本地化字符串。
        /// </summary>
        public static string WarehouseNo {
            get {
                return ResourceManager.GetString("WarehouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可交仓数量 的本地化字符串。
        /// </summary>
        public static string WarehQtyAvailable {
            get {
                return ResourceManager.GetString("WarehQtyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已交仓数量 的本地化字符串。
        /// </summary>
        public static string WarehQtySubmitted {
            get {
                return ResourceManager.GetString("WarehQtySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
