//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_OrderRate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_OrderRate() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_OrderRate", typeof(VT_OrderRate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 达成率 的本地化字符串。
        /// </summary>
        public static string AchieveRate {
            get {
                return ResourceManager.GetString("AchieveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际需求数量 的本地化字符串。
        /// </summary>
        public static string ActualNumberNeed {
            get {
                return ResourceManager.GetString("ActualNumberNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外协 的本地化字符串。
        /// </summary>
        public static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string ClientOrderID {
            get {
                return ResourceManager.GetString("ClientOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划交期 的本地化字符串。
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束 的本地化字符串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单产品进度查询 的本地化字符串。
        /// </summary>
        public static string IIndexTitle {
            get {
                return ResourceManager.GetString("IIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料达成率 的本地化字符串。
        /// </summary>
        public static string MaterialAchieveRate {
            get {
                return ResourceManager.GetString("MaterialAchieveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料名称 的本地化字符串。
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划日期 的本地化字符串。
        /// </summary>
        public static string PlannedDate {
            get {
                return ResourceManager.GetString("PlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划需求数量 的本地化字符串。
        /// </summary>
        public static string PlanNeedNumber {
            get {
                return ResourceManager.GetString("PlanNeedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划数量 的本地化字符串。
        /// </summary>
        public static string PlanQuantity {
            get {
                return ResourceManager.GetString("PlanQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外购 的本地化字符串。
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买数量 的本地化字符串。
        /// </summary>
        public static string PurchaseQuantity {
            get {
                return ResourceManager.GetString("PurchaseQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自加工 的本地化字符串。
        /// </summary>
        public static string SinceProcess {
            get {
                return ResourceManager.GetString("SinceProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁库数量合计 的本地化字符串。
        /// </summary>
        public static string TotalLockNumber {
            get {
                return ResourceManager.GetString("TotalLockNumber", resourceCulture);
            }
        }
    }
}
