//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_ProducePlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_ProducePlan() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_ProducePlan", typeof(VT_ProducePlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 达成率 的本地化字符串。
        /// </summary>
        public static string AchievementRate {
            get {
                return ResourceManager.GetString("AchievementRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string ClientOrderID {
            get {
                return ResourceManager.GetString("ClientOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交货日期 的本地化字符串。
        /// </summary>
        public static string DelvyStartDate {
            get {
                return ResourceManager.GetString("DelvyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划数 的本地化字符串。
        /// </summary>
        public static string PlanQTY {
            get {
                return ResourceManager.GetString("PlanQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产状态 的本地化字符串。
        /// </summary>
        public static string ProduceState {
            get {
                return ResourceManager.GetString("ProduceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产计划总表 的本地化字符串。
        /// </summary>
        public static string ProductionPlan {
            get {
                return ResourceManager.GetString("ProductionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号 的本地化字符串。
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度信息 的本地化字符串。
        /// </summary>
        public static string ProgressInfo {
            get {
                return ResourceManager.GetString("ProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成数量 的本地化字符串。
        /// </summary>
        public static string QTYCompletion {
            get {
                return ResourceManager.GetString("QTYCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未完成数量 的本地化字符串。
        /// </summary>
        public static string QTYUncompletion {
            get {
                return ResourceManager.GetString("QTYUncompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售员 的本地化字符串。
        /// </summary>
        public static string SaleName {
            get {
                return ResourceManager.GetString("SaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度详细 的本地化字符串。
        /// </summary>
        public static string ScheduleInfo {
            get {
                return ResourceManager.GetString("ScheduleInfo", resourceCulture);
            }
        }
    }
}
