//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Produce {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_ProductWarehouse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_ProductWarehouse() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Produce.VT_ProductWarehouse", typeof(VT_ProductWarehouse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 装配小组 的本地化字符串。
        /// </summary>
        public static string AssembleTeam {
            get {
                return ResourceManager.GetString("AssembleTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string BatherID {
            get {
                return ResourceManager.GetString("BatherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱数 的本地化字符串。
        /// </summary>
        public static string BoxQuantity {
            get {
                return ResourceManager.GetString("BoxQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品检验员 的本地化字符串。
        /// </summary>
        public static string CheckPersonName {
            get {
                return ResourceManager.GetString("CheckPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓部门 的本地化字符串。
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门调度员 的本地化字符串。
        /// </summary>
        public static string DispatherPersonName {
            get {
                return ResourceManager.GetString("DispatherPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每箱数量 的本地化字符串。
        /// </summary>
        public static string EachBoxQuantity {
            get {
                return ResourceManager.GetString("EachBoxQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您尚未选中任何记录 的本地化字符串。
        /// </summary>
        public static string NotSelectAny {
            get {
                return ResourceManager.GetString("NotSelectAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无交仓详细信息 的本地化字符串。
        /// </summary>
        public static string NullWarehouseData {
            get {
                return ResourceManager.GetString("NullWarehouseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编号 的本地化字符串。
        /// </summary>
        public static string OrderProductId {
            get {
                return ResourceManager.GetString("OrderProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装情况 的本地化字符串。
        /// </summary>
        public static string PackState {
            get {
                return ResourceManager.GetString("PackState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产成品名称 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        public static string ProductSpecification {
            get {
                return ResourceManager.GetString("ProductSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单详细 的本地化字符串。
        /// </summary>
        public static string ProductWarehouseDetailTabTitle {
            get {
                return ResourceManager.GetString("ProductWarehouseDetailTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓单号 的本地化字符串。
        /// </summary>
        public static string ProductWarehouseID {
            get {
                return ResourceManager.GetString("ProductWarehouseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单打印 的本地化字符串。
        /// </summary>
        public static string ProductWarehousePrintTabTitle {
            get {
                return ResourceManager.GetString("ProductWarehousePrintTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单 的本地化字符串。
        /// </summary>
        public static string ProductWarehouseTitle {
            get {
                return ResourceManager.GetString("ProductWarehouseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单修改 的本地化字符串。
        /// </summary>
        public static string ProductWarehouseUpdateTabTitle {
            get {
                return ResourceManager.GetString("ProductWarehouseUpdateTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格数量 的本地化字符串。
        /// </summary>
        public static string QualifiedQuantity {
            get {
                return ResourceManager.GetString("QualifiedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零头 的本地化字符串。
        /// </summary>
        public static string RemianQuantity {
            get {
                return ResourceManager.GetString("RemianQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除选中的{0}条记录？ 的本地化字符串。
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班组 的本地化字符串。
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓日期 的本地化字符串。
        /// </summary>
        public static string WarehouseDT {
            get {
                return ResourceManager.GetString("WarehouseDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓人 的本地化字符串。
        /// </summary>
        public static string WarehousePersonName {
            get {
                return ResourceManager.GetString("WarehousePersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string WarehouseState {
            get {
                return ResourceManager.GetString("WarehouseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单修改 的本地化字符串。
        /// </summary>
        public static string WarehouseUpdateTabTitle {
            get {
                return ResourceManager.GetString("WarehouseUpdateTabTitle", resourceCulture);
            }
        }
    }
}
