//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Technology {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_ShowProdInfoDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_ShowProdInfoDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Technology.VT_ShowProdInfoDialog", typeof(VT_ShowProdInfoDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 杭州雷迪克汽车部件制造有限公司 的本地化字符串。
        /// </summary>
        public static string CompanyTitleSpan {
            get {
                return ResourceManager.GetString("CompanyTitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称 的本地化字符串。
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧产品名称 的本地化字符串。
        /// </summary>
        public static string OldModelID {
            get {
                return ResourceManager.GetString("OldModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品略称 的本地化字符串。
        /// </summary>
        public static string ProductAbbreviation {
            get {
                return ResourceManager.GetString("ProductAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品类别 的本地化字符串。
        /// </summary>
        public static string ProductCategoryName {
            get {
                return ResourceManager.GetString("ProductCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID 的本地化字符串。
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品信息一览 的本地化字符串。
        /// </summary>
        public static string ProductTitleSpan {
            get {
                return ResourceManager.GetString("ProductTitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料及规格型号 的本地化字符串。
        /// </summary>
        public static string Specifica {
            get {
                return ResourceManager.GetString("Specifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品单位名称 的本地化字符串。
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
    }
}
