//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Store {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_FinOutRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_FinOutRecord() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Store.VT_FinOutRecord", typeof(VT_FinOutRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string ClientOrderID {
            get {
                return ResourceManager.GetString("ClientOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货日期 的本地化字符串。
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货人 的本地化字符串。
        /// </summary>
        public static string DeliveryMan {
            get {
                return ResourceManager.GetString("DeliveryMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货部门 的本地化字符串。
        /// </summary>
        public static string DeliverySection {
            get {
                return ResourceManager.GetString("DeliverySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部成品送货单号 的本地化字符串。
        /// </summary>
        public static string FinInerFinOutID {
            get {
                return ResourceManager.GetString("FinInerFinOutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部成品送货单 的本地化字符串。
        /// </summary>
        public static string FinOutPrintIndexTitle {
            get {
                return ResourceManager.GetString("FinOutPrintIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部成品送货单打印选择 的本地化字符串。
        /// </summary>
        public static string FinOutPrintTitle {
            get {
                return ResourceManager.GetString("FinOutPrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部成品库出库履历详细 的本地化字符串。
        /// </summary>
        public static string FinOutRecordDetlTitle {
            get {
                return ResourceManager.GetString("FinOutRecordDetlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部成品库出库履历一览 的本地化字符串。
        /// </summary>
        public static string FinOutRecordTitle {
            get {
                return ResourceManager.GetString("FinOutRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号 的本地化字符串。
        /// </summary>
        public static string InerFinOutID {
            get {
                return ResourceManager.GetString("InerFinOutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货单号 的本地化字符串。
        /// </summary>
        public static string LadiID {
            get {
                return ResourceManager.GetString("LadiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷迪克内部成品送货单 的本地化字符串。
        /// </summary>
        public static string LDKFinOutPrintIndexTitle {
            get {
                return ResourceManager.GetString("LDKFinOutPrintIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库日期 的本地化字符串。
        /// </summary>
        public static string OutDate {
            get {
                return ResourceManager.GetString("OutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库人 的本地化字符串。
        /// </summary>
        public static string OutWorks {
            get {
                return ResourceManager.GetString("OutWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编号 的本地化字符串。
        /// </summary>
        public static string PartAbbrevi {
            get {
                return ResourceManager.GetString("PartAbbrevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打印 的本地化字符串。
        /// </summary>
        public static string Printed {
            get {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 印刷标志 的本地化字符串。
        /// </summary>
        public static string PrintFlag {
            get {
                return ResourceManager.GetString("PrintFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货日期 的本地化字符串。
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人 的本地化字符串。
        /// </summary>
        public static string ReceiptMan {
            get {
                return ResourceManager.GetString("ReceiptMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货部门 的本地化字符串。
        /// </summary>
        public static string ReceiptSection {
            get {
                return ResourceManager.GetString("ReceiptSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打印 的本地化字符串。
        /// </summary>
        public static string UnPrint {
            get {
                return ResourceManager.GetString("UnPrint", resourceCulture);
            }
        }
    }
}
