//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Store {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_FinInRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_FinInRecord() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Store.VT_FinInRecord", typeof(VT_FinInRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string BatchID {
            get {
                return ResourceManager.GetString("BatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string ClientOrderID {
            get {
                return ResourceManager.GetString("ClientOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库履历详细 的本地化字符串。
        /// </summary>
        public static string FinInRecordDtlTitle {
            get {
                return ResourceManager.GetString("FinInRecordDtlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库履历一览 的本地化字符串。
        /// </summary>
        public static string FinInRecordTitle {
            get {
                return ResourceManager.GetString("FinInRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待入库一览 的本地化字符串。
        /// </summary>
        public static string FinInStoreTitle {
            get {
                return ResourceManager.GetString("FinInStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string InCls {
            get {
                return ResourceManager.GetString("InCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库日期 的本地化字符串。
        /// </summary>
        public static string InDate {
            get {
                return ResourceManager.GetString("InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库移动区分 的本地化字符串。
        /// </summary>
        public static string InMoveCls {
            get {
                return ResourceManager.GetString("InMoveCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移库 的本地化字符串。
        /// </summary>
        public static string MoveCls {
            get {
                return ResourceManager.GetString("MoveCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编号 的本地化字符串。
        /// </summary>
        public static string PartAbbrevi {
            get {
                return ResourceManager.GetString("PartAbbrevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单号 的本地化字符串。
        /// </summary>
        public static string PlanID {
            get {
                return ResourceManager.GetString("PlanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库 的本地化字符串。
        /// </summary>
        public static string WareHouse {
            get {
                return ResourceManager.GetString("WareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓管员 的本地化字符串。
        /// </summary>
        public static string WareHouseKpID {
            get {
                return ResourceManager.GetString("WareHouseKpID", resourceCulture);
            }
        }
    }
}
