//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Market {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_OrderBillManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_OrderBillManage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Market.VT_OrderBillManage", typeof(VT_OrderBillManage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string ApprovalUserNameSpan {
            get {
                return ResourceManager.GetString("ApprovalUserNameSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string ClientNameSpan {
            get {
                return ResourceManager.GetString("ClientNameSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string ClientOrderDetail {
            get {
                return ResourceManager.GetString("ClientOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string ClientOrderIDSpan {
            get {
                return ResourceManager.GetString("ClientOrderIDSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单 的本地化字符串。
        /// </summary>
        public static string ClientOrderSpan {
            get {
                return ResourceManager.GetString("ClientOrderSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户型号 的本地化字符串。
        /// </summary>
        public static string ClientProductID {
            get {
                return ResourceManager.GetString("ClientProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杭州雷迪克汽车部件制造有限公司 的本地化字符串。
        /// </summary>
        public static string CompanyTitleSpan {
            get {
                return ResourceManager.GetString("CompanyTitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打字内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除该条记录？ 的本地化字符串。
        /// </summary>
        public static string DeleteInformation {
            get {
                return ResourceManager.GetString("DeleteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交货日期 的本地化字符串。
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编制 的本地化字符串。
        /// </summary>
        public static string EditUserNameSpan {
            get {
                return ResourceManager.GetString("EditUserNameSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二、有关油封要求 的本地化字符串。
        /// </summary>
        public static string ODCTRequireSpan {
            get {
                return ResourceManager.GetString("ODCTRequireSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、有关打字要求 的本地化字符串。
        /// </summary>
        public static string ODPTRequireSpan {
            get {
                return ResourceManager.GetString("ODPTRequireSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同规定货物之型号、数量、打字要求等 的本地化字符串。
        /// </summary>
        public static string ODTRequireSpan {
            get {
                return ResourceManager.GetString("ODTRequireSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四、其他注意事项 的本地化字符串。
        /// </summary>
        public static string OtherMatterSpan {
            get {
                return ResourceManager.GetString("OtherMatterSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装箱数 的本地化字符串。
        /// </summary>
        public static string PackageQuantity {
            get {
                return ResourceManager.GetString("PackageQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三、有关包装要求 的本地化字符串。
        /// </summary>
        public static string PackageRequireSpan {
            get {
                return ResourceManager.GetString("PackageRequireSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸箱尺寸 的本地化字符串。
        /// </summary>
        public static string PackageSize {
            get {
                return ResourceManager.GetString("PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打字位置 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产单元区分 的本地化字符串。
        /// </summary>
        public static string ProduceCellID {
            get {
                return ResourceManager.GetString("ProduceCellID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产单元 的本地化字符串。
        /// </summary>
        public static string ProduceCellName {
            get {
                return ResourceManager.GetString("ProduceCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该合同下共涉及以下生产单元 的本地化字符串。
        /// </summary>
        public static string ProduceCellNameSpan {
            get {
                return ResourceManager.GetString("ProduceCellNameSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我司型号 的本地化字符串。
        /// </summary>
        public static string ProductAbbreviation {
            get {
                return ResourceManager.GetString("ProductAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID 的本地化字符串。
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油封颜色 的本地化字符串。
        /// </summary>
        public static string SealColorID {
            get {
                return ResourceManager.GetString("SealColorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油封其他特殊要求(如打字等) 的本地化字符串。
        /// </summary>
        public static string SealRequire {
            get {
                return ResourceManager.GetString("SealRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传图片 的本地化字符串。
        /// </summary>
        public static string UploadSpan {
            get {
                return ResourceManager.GetString("UploadSpan", resourceCulture);
            }
        }
    }
}
