//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Market {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_ShowMarketClientInfoDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_ShowMarketClientInfoDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Market.VT_ShowMarketClientInfoDialog", typeof(VT_ShowMarketClientInfoDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 公司地址 的本地化字符串。
        /// </summary>
        public static string ClientAddress {
            get {
                return ResourceManager.GetString("ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户ID 的本地化字符串。
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户等级 的本地化字符串。
        /// </summary>
        public static string ClientLevel {
            get {
                return ResourceManager.GetString("ClientLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司简称 的本地化字符串。
        /// </summary>
        public static string ClientNO {
            get {
                return ResourceManager.GetString("ClientNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        public static string ClientZipCode {
            get {
                return ResourceManager.GetString("ClientZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杭州雷迪克汽车部件制造有限公司 的本地化字符串。
        /// </summary>
        public static string CompanyTitleSpan {
            get {
                return ResourceManager.GetString("CompanyTitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位区分 的本地化字符串。
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人姓名 的本地化字符串。
        /// </summary>
        public static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信誉等级 的本地化字符串。
        /// </summary>
        public static string CreditLevel {
            get {
                return ResourceManager.GetString("CreditLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真1 的本地化字符串。
        /// </summary>
        public static string Fax1 {
            get {
                return ResourceManager.GetString("Fax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真2 的本地化字符串。
        /// </summary>
        public static string Fax2 {
            get {
                return ResourceManager.GetString("Fax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户信息一览 的本地化字符串。
        /// </summary>
        public static string MarketClientTitleSpan {
            get {
                return ResourceManager.GetString("MarketClientTitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话1 的本地化字符串。
        /// </summary>
        public static string TelephoneNO1 {
            get {
                return ResourceManager.GetString("TelephoneNO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话2 的本地化字符串。
        /// </summary>
        public static string TelephoneNO2 {
            get {
                return ResourceManager.GetString("TelephoneNO2", resourceCulture);
            }
        }
    }
}
