//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Common.VT_Common", typeof(VT_Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请 的本地化字符串。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string BackStep {
            get {
                return ResourceManager.GetString("BackStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消报废 的本地化字符串。
        /// </summary>
        public static string CancelDiscard {
            get {
                return ResourceManager.GetString("CancelDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订单 的本地化字符串。
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产能分析 的本地化字符串。
        /// </summary>
        public static string CapacityAnalysis {
            get {
                return ResourceManager.GetString("CapacityAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杭州雷迪克汽车部件制造有限公司 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认要删除这些信息吗? 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认排产 的本地化字符串。
        /// </summary>
        public static string ConfirmedProduction {
            get {
                return ResourceManager.GetString("ConfirmedProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成工票 的本地化字符串。
        /// </summary>
        public static string CreateTicket {
            get {
                return ResourceManager.GetString("CreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败,请重新操作 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细... 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废 的本地化字符串。
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ensure {
            get {
                return ResourceManager.GetString("Ensure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装排产 的本地化字符串。
        /// </summary>
        public static string ErectionProduction {
            get {
                return ResourceManager.GetString("ErectionProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string Examine {
            get {
                return ResourceManager.GetString("Examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看甘特图 的本地化字符串。
        /// </summary>
        public static string GanttChart {
            get {
                return ResourceManager.GetString("GanttChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工登录 的本地化字符串。
        /// </summary>
        public static string HandLanding {
            get {
                return ResourceManager.GetString("HandLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string InStorage {
            get {
                return ResourceManager.GetString("InStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开具领料单 的本地化字符串。
        /// </summary>
        public static string IssueRequisitions {
            get {
                return ResourceManager.GetString("IssueRequisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Landing {
            get {
                return ResourceManager.GetString("Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行追加 的本地化字符串。
        /// </summary>
        public static string LineAddittion {
            get {
                return ResourceManager.GetString("LineAddittion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}失败！ 的本地化字符串。
        /// </summary>
        public static string MAddFailed {
            get {
                return ResourceManager.GetString("MAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}成功！ 的本地化字符串。
        /// </summary>
        public static string MAddSuccess {
            get {
                return ResourceManager.GetString("MAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料确认 的本地化字符串。
        /// </summary>
        public static string MaterialConfirm {
            get {
                return ResourceManager.GetString("MaterialConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 的本地化字符串。
        /// </summary>
        public static string OutStorage {
            get {
                return ResourceManager.GetString("OutStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要操作的数据 的本地化字符串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印预览 的本地化字符串。
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工排产 的本地化字符串。
        /// </summary>
        public static string ProcessProduction {
            get {
                return ResourceManager.GetString("ProcessProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排产解除 的本地化字符串。
        /// </summary>
        public static string ProductionRelease {
            get {
                return ResourceManager.GetString("ProductionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批准 的本地化字符串。
        /// </summary>
        public static string Sanction {
            get {
                return ResourceManager.GetString("Sanction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单生成 的本地化字符串。
        /// </summary>
        public static string SchedulingNotice {
            get {
                return ResourceManager.GetString("SchedulingNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓管员 的本地化字符串。
        /// </summary>
        public static string StoreManager {
            get {
                return ResourceManager.GetString("StoreManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务接收 的本地化字符串。
        /// </summary>
        public static string TaskReceiving {
            get {
                return ResourceManager.GetString("TaskReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 友情提示 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工流转卡 的本地化字符串。
        /// </summary>
        public static string TransferCard {
            get {
                return ResourceManager.GetString("TransferCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string ViewEyes {
            get {
                return ResourceManager.GetString("ViewEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓 的本地化字符串。
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
    }
}
