//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ClientMessage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CM_Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CM_Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ClientMessage.CM_Common", typeof(CM_Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空！ 的本地化字符串。
        /// </summary>
        public static string CK0001 {
            get {
                return ResourceManager.GetString("CK0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除本条记录吗？ 的本地化字符串。
        /// </summary>
        public static string DLG0001 {
            get {
                return ResourceManager.GetString("DLG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求服务器失败，请刷新页面重试！ 的本地化字符串。
        /// </summary>
        public static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        public static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        public static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        public static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string MSG005 {
            get {
                return ResourceManager.GetString("MSG005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数字！ 的本地化字符串。
        /// </summary>
        public static string MSG40301001 {
            get {
                return ResourceManager.GetString("MSG40301001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入不能为空！ 的本地化字符串。
        /// </summary>
        public static string MSG40301002 {
            get {
                return ResourceManager.GetString("MSG40301002", resourceCulture);
            }
        }
    }
}
