//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ClientMessage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CM_Produce {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CM_Produce() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ClientMessage.CM_Produce", typeof(CM_Produce).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CK4100属于加工管理 的本地化字符串。
        /// </summary>
        public static string CK40104000 {
            get {
                return ResourceManager.GetString("CK40104000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的记录中含有多种\&quot;&lt;font style=&apos;color:red&apos;&gt;零件型号&lt;/font&gt;\&quot;，请重新选择 的本地化字符串。
        /// </summary>
        public static string CK40104001 {
            get {
                return ResourceManager.GetString("CK40104001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的记录中含有多种\&quot;&lt;font style=&apos;color:red&apos;&gt;材料和规格要求&lt;/font&gt;\&quot;，请重新选择 的本地化字符串。
        /// </summary>
        public static string CK40104002 {
            get {
                return ResourceManager.GetString("CK40104002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的记录中含有\&quot;&lt;font style=&apos;color:red&apos;&gt;原料数量&lt;/font&gt;\&quot;为0的记录，请重新选择 的本地化字符串。
        /// </summary>
        public static string CK40104003 {
            get {
                return ResourceManager.GetString("CK40104003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选中一行 的本地化字符串。
        /// </summary>
        public static string CK40104004 {
            get {
                return ResourceManager.GetString("CK40104004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string CK40502000 {
            get {
                return ResourceManager.GetString("CK40502000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多只能选择一条记录！ 的本地化字符串。
        /// </summary>
        public static string CK40502001 {
            get {
                return ResourceManager.GetString("CK40502001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一条记录！ 的本地化字符串。
        /// </summary>
        public static string CK40502002 {
            get {
                return ResourceManager.GetString("CK40502002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除选中的成品交仓单吗？ 的本地化字符串。
        /// </summary>
        public static string CK40502003 {
            get {
                return ResourceManager.GetString("CK40502003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您尚未选中任何记录！ 的本地化字符串。
        /// </summary>
        public static string CK40502004 {
            get {
                return ResourceManager.GetString("CK40502004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除已入库的交仓单！ 的本地化字符串。
        /// </summary>
        public static string CK40502005 {
            get {
                return ResourceManager.GetString("CK40502005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法修改已入库的交仓单 的本地化字符串。
        /// </summary>
        public static string CK40502006 {
            get {
                return ResourceManager.GetString("CK40502006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “&lt;font style=&apos;color:red;&apos;&gt;{0}&lt;/font&gt;”不允许为空！ 的本地化字符串。
        /// </summary>
        public static string CK40502007 {
            get {
                return ResourceManager.GetString("CK40502007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLG4100属于加工管理 的本地化字符串。
        /// </summary>
        public static string DLG40104000 {
            get {
                return ResourceManager.GetString("DLG40104000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已修改，是否保存？ 的本地化字符串。
        /// </summary>
        public static string DLG40104001 {
            get {
                return ResourceManager.GetString("DLG40104001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSG401040属于加工管理 的本地化字符串。
        /// </summary>
        public static string MSG40104000 {
            get {
                return ResourceManager.GetString("MSG40104000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许大于修改前的计划装配数量 的本地化字符串。
        /// </summary>
        public static string MSG40301001 {
            get {
                return ResourceManager.GetString("MSG40301001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非未生成工票状态不能进行编辑 的本地化字符串。
        /// </summary>
        public static string MSG40301002 {
            get {
                return ResourceManager.GetString("MSG40301002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下单日期不允许为空 的本地化字符串。
        /// </summary>
        public static string MSG40301003 {
            get {
                return ResourceManager.GetString("MSG40301003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交仓 的本地化字符串。
        /// </summary>
        public static string MSG40401001 {
            get {
                return ResourceManager.GetString("MSG40401001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法在订单表中取得相应的产品型号和订单详细 的本地化字符串。
        /// </summary>
        public static string MSG40601001 {
            get {
                return ResourceManager.GetString("MSG40601001", resourceCulture);
            }
        }
    }
}
