//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Purchase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_DeliveryOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_DeliveryOrder() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Purchase.VT_DeliveryOrder", typeof(VT_DeliveryOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 供货商 的本地化字符串。
        /// </summary>
        public static string DCompany {
            get {
                return ResourceManager.GetString("DCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单位 的本地化字符串。
        /// </summary>
        public static string DCompanyID {
            get {
                return ResourceManager.GetString("DCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货日期 的本地化字符串。
        /// </summary>
        public static string DDate {
            get {
                return ResourceManager.GetString("DDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产部门 的本地化字符串。
        /// </summary>
        public static string DeptName {
            get {
                return ResourceManager.GetString("DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号 的本地化字符串。
        /// </summary>
        public static string DOrderID {
            get {
                return ResourceManager.GetString("DOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单状态 的本地化字符串。
        /// </summary>
        public static string DOrderStatus {
            get {
                return ResourceManager.GetString("DOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购类别 的本地化字符串。
        /// </summary>
        public static string DOrderType {
            get {
                return ResourceManager.GetString("DOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货人 的本地化字符串。
        /// </summary>
        public static string DUID {
            get {
                return ResourceManager.GetString("DUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单 的本地化字符串。
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单一览 的本地化字符串。
        /// </summary>
        public static string InitTitle {
            get {
                return ResourceManager.GetString("InitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购计划单号 的本地化字符串。
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string OrdNo {
            get {
                return ResourceManager.GetString("OrdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位 的本地化字符串。
        /// </summary>
        public static string RecCompanyID {
            get {
                return ResourceManager.GetString("RecCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杭州雷迪克汽车部件有限公司 的本地化字符串。
        /// </summary>
        public static string RecCompanyName {
            get {
                return ResourceManager.GetString("RecCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        public static string TelNo {
            get {
                return ResourceManager.GetString("TelNo", resourceCulture);
            }
        }
    }
}
