//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Purchase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_PurchaseOrderList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_PurchaseOrderList() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Purchase.VT_PurchaseOrderList", typeof(VT_PurchaseOrderList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 批准日期 的本地化字符串。
        /// </summary>
        public static string ApproveDate {
            get {
                return ResourceManager.GetString("ApproveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批准 的本地化字符串。
        /// </summary>
        public static string ApproveUID {
            get {
                return ResourceManager.GetString("ApproveUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承接单位 的本地化字符串。
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供货商 的本地化字符串。
        /// </summary>
        public static string CompName {
            get {
                return ResourceManager.GetString("CompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string CustomerOrder {
            get {
                return ResourceManager.GetString("CustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产部门 的本地化字符串。
        /// </summary>
        public static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门 的本地化字符串。
        /// </summary>
        public static string DeptName {
            get {
                return ResourceManager.GetString("DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外购产品计划单 的本地化字符串。
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编制日期 的本地化字符串。
        /// </summary>
        public static string EstablishDate {
            get {
                return ResourceManager.GetString("EstablishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编制人 的本地化字符串。
        /// </summary>
        public static string EstablishUID {
            get {
                return ResourceManager.GetString("EstablishUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下单日期 的本地化字符串。
        /// </summary>
        public static string EstDate {
            get {
                return ResourceManager.GetString("EstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编制 的本地化字符串。
        /// </summary>
        public static string EstUID {
            get {
                return ResourceManager.GetString("EstUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAX 的本地化字符串。
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品外购单一览 的本地化字符串。
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外购产品计划单号 的本地化字符串。
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外购单号 的本地化字符串。
        /// </summary>
        public static string OutOrderID {
            get {
                return ResourceManager.GetString("OutOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态 的本地化字符串。
        /// </summary>
        public static string OutOrderStatus {
            get {
                return ResourceManager.GetString("OutOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注:(256文字) 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收 的本地化字符串。
        /// </summary>
        public static string SignUID {
            get {
                return ResourceManager.GetString("SignUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急状态 的本地化字符串。
        /// </summary>
        public static string UrgentStatus {
            get {
                return ResourceManager.GetString("UrgentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加急 的本地化字符串。
        /// </summary>
        public static string UrgentStatus1 {
            get {
                return ResourceManager.GetString("UrgentStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急 的本地化字符串。
        /// </summary>
        public static string UrgentStatus2 {
            get {
                return ResourceManager.GetString("UrgentStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string VerifyUID {
            get {
                return ResourceManager.GetString("VerifyUID", resourceCulture);
            }
        }
    }
}
