//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_UI.Resource.ViewText.Purchase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VT_SupplierOrderList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VT_SupplierOrderList() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_UI.Resource.ViewText.Purchase.VT_SupplierOrderList", typeof(VT_SupplierOrderList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门 的本地化字符串。
        /// </summary>
        public static string BelongDepartment {
            get {
                return ResourceManager.GetString("BelongDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态 的本地化字符串。
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号 的本地化字符串。
        /// </summary>
        public static string CustomerOrderID {
            get {
                return ResourceManager.GetString("CustomerOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调入单位 的本地化字符串。
        /// </summary>
        public static string InCompany {
            get {
                return ResourceManager.GetString("InCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品外协加工调度（注塑）单一览 的本地化字符串。
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下单日期 的本地化字符串。
        /// </summary>
        public static string MarkDate {
            get {
                return ResourceManager.GetString("MarkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单日期 的本地化字符串。
        /// </summary>
        public static string MarkDateFrom {
            get {
                return ResourceManager.GetString("MarkDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~ 的本地化字符串。
        /// </summary>
        public static string MarkDateTo {
            get {
                return ResourceManager.GetString("MarkDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单人 的本地化字符串。
        /// </summary>
        public static string MarkUser {
            get {
                return ResourceManager.GetString("MarkUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据种类 的本地化字符串。
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调出单位 的本地化字符串。
        /// </summary>
        public static string OutCompany {
            get {
                return ResourceManager.GetString("OutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产部门 的本地化字符串。
        /// </summary>
        public static string ProduceDepartment {
            get {
                return ResourceManager.GetString("ProduceDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产主管 的本地化字符串。
        /// </summary>
        public static string ProduceManager {
            get {
                return ResourceManager.GetString("ProduceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外协单号 的本地化字符串。
        /// </summary>
        public static string SupplierOrderNo {
            get {
                return ResourceManager.GetString("SupplierOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急状态 的本地化字符串。
        /// </summary>
        public static string UrgentStatus {
            get {
                return ResourceManager.GetString("UrgentStatus", resourceCulture);
            }
        }
    }
}
