//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServerMessage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SM_FAScheduleBill {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SM_FAScheduleBill() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.ServerMessage.SM_FAScheduleBill", typeof(SM_FAScheduleBill).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 生成总装大工票失败！ 的本地化字符串。
        /// </summary>
        public static string ECreateAssemBillError {
            get {
                return ResourceManager.GetString("ECreateAssemBillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        public static string ESaveError {
            get {
                return ResourceManager.GetString("ESaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单：{0}，在成品构成表中不存在对应的子工序ID，无法生成总装大工票！ 的本地化字符串。
        /// </summary>
        public static string ESubProcIDNotExist {
            get {
                return ResourceManager.GetString("ESubProcIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功生成总装工票及详细。 的本地化字符串。
        /// </summary>
        public static string MCreateSuccess {
            get {
                return ResourceManager.GetString("MCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装调度单删除成功 的本地化字符串。
        /// </summary>
        public static string MDeleteSuccess {
            get {
                return ResourceManager.GetString("MDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string MSaveSuccess {
            get {
                return ResourceManager.GetString("MSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置： 的本地化字符串。
        /// </summary>
        public static string MTyping1 {
            get {
                return ResourceManager.GetString("MTyping1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容： 的本地化字符串。
        /// </summary>
        public static string MTyping2 {
            get {
                return ResourceManager.GetString("MTyping2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总装调度单:{0}的实际装配数量{1}大于0，不允许删除！ 的本地化字符串。
        /// </summary>
        public static string WActualNumber {
            get {
                return ResourceManager.GetString("WActualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单号：{0}已存在对应的总装工票！ 的本地化字符串。
        /// </summary>
        public static string WAssemBillExist {
            get {
                return ResourceManager.GetString("WAssemBillExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划装配数量必须大于实际装配数量 的本地化字符串。
        /// </summary>
        public static string WPlanLessThenActual {
            get {
                return ResourceManager.GetString("WPlanLessThenActual", resourceCulture);
            }
        }
    }
}
