//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServerMessage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SM_Purchase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SM_Purchase() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.ServerMessage.SM_Purchase", typeof(SM_Purchase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的客户订单号不存在，请输入正确的客户订单号！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00001 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未输入的承接单位，请查询后输入正确的承接单位 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00002 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的承接单位不正确，请查询后重新输入有效的承接单位 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00003 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有选择任何采购物料，请您选择您所需要采购的物料 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00004 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的物料编号未输入，请查询后输入正确的物料编号 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00005 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的数量为无效数据，请您输入正确的数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00006 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的材料规格及要求的BYTE数超过200BYTE，请您重新输入正确的材料规格及要求 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00007 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的单价的BYTE数超过10BYTE，请您重新输入正确的单价 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00008 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的单价为无效数值，请您重新输入正确的有效单价 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00009 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的交货日期未输入，请您重新输入正确的有效日期 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00010 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的交货日期为无效日期，请您输入正确的交货日期 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00011 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的版本号的BYTE数超过40BYTE，请您重新输入正确的版本号 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00012 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的备注的BYTE数超过512BYTE，请您重新输入正确的备注 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00013 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的注:(256文字)的BYTE数超过512BYTE，请您重新输入正确的注:(256文字) 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00014 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的FAX为无效FAX，请您输入正确的FAX 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00015 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的FAX的BYTE数超过20BYTE，请您重新输入正确的FAX 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00016 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的批准人超过了10个字节，请您重新输入 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00017 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的审核人超过了10个字节，请您重新输入 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00018 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的编制人超过了10个字节，请您重新输入 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00019 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的签收人超过了10个字节，请您重新输入 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00020 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有选择要删除的对象，请您选择要删除的对象！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00021 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的外购单{0}已被批准，不可重复批准。 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00022 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的外购单{0}已通过审核，不可重复审核。 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00023 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已被签收的外购单不可以被删除，您选择的外购单{0}已被签收，请您重新选择要删除的对象。 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00024 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已被经办的外协加工调度单不可以被删除，您选择的外协加工调度单{0}已经办，请您重新选择要删除的对象。 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00025 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的估价未输入，请您输入正确的数字 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00026 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的单位未输入，请您输入正确的数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00027 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的加工工艺未输入，请您输入正确的数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00028 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调入单位为空，请输入调入单位 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00029 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单种类未选择，请选择调度单种类 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00030 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单紧急状态未选择，请选择调度单的紧急状态 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00031 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单所属单位未选择，请选择调度单的所属单位 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00032 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未填写需要添加的数据，请填写正确的数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00033 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00034 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的采购计划单号有误，请查询后输入正确的采购计划单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00035 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的采购计划单号不存在，请重新输入正确的采购计划单号！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00036 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未输入采购计划单号，请输入 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00037 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未输入的所属部门，请查询后输入正确的所属部门 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00038 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的估价的BYTE数超过10BYTE，请您重新输入正确的估价 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00039 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的估价为无效数值，请您重新输入正确的有效估价 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00040 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的计划单号的BYTE数超过20BYTE，请您重新输入正确的计划单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00041 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的数量的BYTE数超过10BYTE，请您重新输入正确的数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00042 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号为{0}的送货单信息有误，请重新确认后再进行操作！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00043 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号为{0}的送货单已进行过审核操作，不可重复审核！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00044 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号为{0}的送货单已打印，不可删除！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00045 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行输入的估价为无效数值，请您重新输入正确的有效估价 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00046 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该外购单还未批准，请先批准再签收 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00047 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批准人未指定时，不可进行批准操作。请选择批准人后再进行批准操作 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00048 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核人未指定时，不可进行审核操作。请选择审核人后再进行审核操作 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00049 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的客户订单号不正确，请查询后输入正确的客户订单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00050 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该外购单状态不是已签收，请签收后再打印 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00051 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的每件数量未输入，请输入正确的每件数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00052 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【每件数量】栏输入不正确，请输入正确的每件数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00053 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【每件数量】栏输入的内容大于10字节，请重新输入10字节以内的每件数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00054 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的件数未输入，请输入正确的件数 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00055 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【件数】栏输入不正确，请输入正确的件数 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00056 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【件数】栏输入的内容大于10字节，请重新输入10字节以内的件数 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00057 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的零头未输入，请输入正确的零头 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00058 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【零头】栏输入不正确，请输入正确的零头 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00059 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【零头】栏输入的内容大于10字节，请重新输入10字节以内的零头 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00060 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的实收数量未输入，请输入正确的实收数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00061 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【实收数量】栏输入不正确，请输入正确的实收数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00062 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【实收数量】栏输入的内容大于10字节，请重新输入10字节以内的实收数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00063 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【备注】栏输入的内容大于512字节，请重新输入512字节以内的备注 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00064 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面输入的采购计划单号已发生变化，请按下【导入】按钮后，重新导入采购计划单数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00065 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【供货商】栏未输入，请选择供货商&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00066 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【单价】栏未输入，请输入有效的单价&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00067 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【单价】栏输入内容已超过{1}BYTE数，请输入有效的单价&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00068 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【估价】栏未输入，请输入有效的估价&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00069 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【估价】栏输入内容已超过{1}BYTE数，请输入有效的估价&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00070 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【采购数量】栏未输入，请输入有效的采购数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00071 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【采购数量】栏输入的数量大于待购数量，请输入有效的采购数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00072 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【采购数量】栏输入内容已超过{1}BYTE数，请输入有效的采购数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00073 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【外协数量】栏未输入，请输入有效的外协数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00074 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【外协数量】栏输入的数量大于待购数量，请输入有效的外协数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00075 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【外协数量】栏输入内容已超过{1}BYTE数，请输入有效的外协数量&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00076 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的【外协单位】栏未输入，请选择外协单位&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_E00077 {
            get {
                return ResourceManager.GetString("SMSG_PUR_E00077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string SMSG_PUR_S00001 {
            get {
                return ResourceManager.GetString("SMSG_PUR_S00001", resourceCulture);
            }
        }
    }
}
