//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServerMessage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SM_Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SM_Store() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.ServerMessage.SM_Store", typeof(SM_Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的数据仓库预约详细表里不存在，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00001 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的检验单号输入不合法，请您输入正确的检验单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000010 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的物料编号输入不合法，请您输入正确的物料编号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000011 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的合格数量输入不合法，请您输入正确的合格数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000012 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的每箱数量输入不合法，请您输入正确的每箱数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000013 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的箱数输入不合法，请您输入正确的箱数 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000014 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的零头输入不合法，请您输入正确的零头 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000015 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单号不存在，请您输入正确的成品交仓单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000016 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号不存在，请您输入正确的批次号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000017 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的计划单号不存在，请您输入正确的计划单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000018 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的检验单号不存在，请您输入正确的检验单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000019 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单号未输入，请您输入正确的成品交仓单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00002 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的物料编号不存在，请您输入正确的物料编号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000020 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的交仓详细数据不存在，请您输入正确的数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000021 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的合格数量未输入，请您输入正确的合格数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000022 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的每箱数量未输入，请您输入正确的每箱数量 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000023 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的箱数未输入，请您输入正确的箱数 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000024 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的零头未输入，请您输入正确的零头 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E000025 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号未输入，请您输入正确的批次号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00003 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的计划单号未输入，请您输入正确的计划单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00004 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的检验单号未输入，请您输入正确的检验单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00005 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的物料编号未输入，请您输入正确的物料编号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00006 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品交仓单号输入不合法，请您输入正确的成品交仓单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00007 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号输入不合法，请您输入正确的批次号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00008 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行的计划单号输入不合法，请您输入正确的计划单号 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E00009 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次别库存表中不存在此条数据 的本地化字符串。
        /// </summary>
        internal static string SMSG_STORE_E10001 {
            get {
                return ResourceManager.GetString("SMSG_STORE_E10001", resourceCulture);
            }
        }
    }
}
